### ISSUE TITLE
corebird visual issues

### ISSUE THREAD

**Issue by alphaPhi** [poltertec/evopop-gtk-theme#12]
Hovering the text may render it unreadable in some screens without perfect contrast. Maybe a darker grey(or with some blue tone) could be used to increase the contrast. 
Also the black lines separating the tweets are quit distracting, in Adwaita the use a light grey color.

![corebird-issues](https://cloud.githubusercontent.com/assets/4603691/6459489/c5c9ce8a-c197-11e4-8697-a2fbe7ef5f65.png)

**Comment by ryanleesipes** [comment]
Going to follow @hackaday because of this post. :)

**Comment by alphaPhi** [comment]
huh :P
