### ISSUE TITLE
Support for GTK+ 3.16

### ISSUE THREAD

**Issue by bmeznarsic** [poltertec/evopop-gtk-theme#19]
I hear Justin is already building GNOME/GTK+ packages. Might wanna start porting to v3.16.

**Comment by poltertec** [comment]
Love to as soon as  i can get my hands on the gtk 3.16 package.
Only using evolve atm :)

**Comment by Justinzobel** [comment]
@poltertec come at me on IRC and i'll send you the gtk3.16 packags :)
