### ISSUE TITLE
Theming bugs

### ISSUE THREAD

**Issue by pulb** [poltertec/evopop-gtk-theme#20]
Hi, awesome theme!

I found a few theming issues though. The first screenshot shows an oversized close button in a Gimp tool window, the second shows the unthemed resize handle in Nautilus. I'm using GNOME 3.14.

![bildschirmfoto von 2015-03-28 12 14 00](https://cloud.githubusercontent.com/assets/827576/6880869/7a306b76-d544-11e4-84c2-0e984c64e6f7.png)
![bildschirmfoto von 2015-03-28 12 10 18](https://cloud.githubusercontent.com/assets/827576/6880870/7a3328a2-d544-11e4-8902-fa08f898aa98.png)

**Comment by poltertec** [comment]
Heya :)
Thx for pointing out the close button issue.
Changed the pane-handle to something more fitting for the theme.

**Comment by pulb** [comment]
Many thanks for fixing it so quickly. Though what I meant with "resize handle" was actually the whole vertical grey line (including the dots) :-) I think it would look better if that line isn't visible, just like in the Adwaita theme.

**Comment by pulb** [comment]
Oh and what about using a slightly darker grey in Nautilus' side bar, so there's more contrast to the files pane on the right side?

**Comment by poltertec** [comment]
Ow :) 
Still weighing or options with that sidebar, but is deffinitly being worked on.
