### ISSUE TITLE
No Firefox theming

### ISSUE THREAD

**Issue by zesterer** [poltertec/evopop-gtk-theme#22]
I've noticed that this theme provides no Firefox theming, while other themes do. Is this because Firefox utilises Gtk 2 and this theme is Gtk 3 only? Regardless it's a little disappointing, since Firefox doesn't look very good without the dark tab background...

**Comment by poltertec** [comment]
Will be addressed soon still lots todo on the gtk2 front

**Comment by zesterer** [comment]
Yay! That's awesome.

**Comment by poltertec** [comment]
firefox issue should be resolved :)

**Comment by zesterer** [comment]
I'll give it a go now...
