### ISSUE TITLE
Pantheon Notifications transparency issues

### ISSUE THREAD

**Issue by zesterer** [poltertec/evopop-gtk-theme#23]
![screenshot from 2015-03-28 14 33 07](https://cloud.githubusercontent.com/assets/3268430/6881431/72b6730a-d557-11e4-951b-feafab79768c.png)

As you can see here, this theme display transparent notifications. Clearly this isn't the intended behaviour. It would be brilliant if this could be fixed :-)

**Comment by DerpyCrabs** [comment]
it is fixed by adding:
```
.gala-notification {
    border: none;
    border-radius: 4px;
    background-color: @bg_color;
    background-image: none;
```
to gtk-widgets.css file.

**Comment by poltertec** [comment]
thx no class searching :)

**Comment by zesterer** [comment]
Hello,

I love the fix, but there's a problem. It creases a white background, while the text is very close to white so it's almost invisible. Maybe the background colour should become more like the headerbar background colour?

**Comment by DerpyCrabs** [comment]
I didn't notice that i used bg_color in code. I'm using dark variant and it has headerbar background colour for notification. This bug can be fixed by changing @bg_color with #31363D.

**Comment by poltertec** [comment]
Text must be controlled separatly then, color was set.
But will switch to header color to fix the normal theme.
Light theme won't be fixed though.

**Comment by zesterer** [comment]
That's all fine with me, I prefer the default theme :-)

Thanks.
