### ISSUE TITLE
Permissions 

### ISSUE THREAD

**Issue by DerpyCrabs** [poltertec/evopop-gtk-theme#29]
After install, folders with theme in /usr/share/themes have 700 permissions. It didn't allow to set theme. Changing permissions to 755 (as another theme folders) recursively fixes this bug.

**Comment by poltertec** [comment]
Wierd all permissions seem correct here :s

**Comment by DerpyCrabs** [comment]
With 700 permissions, after applying theme, theme changes to adwaita.
![screenshot from 2015-03-30 16 36 38](https://cloud.githubusercontent.com/assets/9917318/6893904/97418f88-d6f2-11e4-9ff4-50074394da3e.png)
(Left is permissions after installing with sudo make install, right is working themes from repository)

**Comment by poltertec** [comment]
I did not say i didn't believe you :)
However have no direct idea what is causing this on your system.
Just tried it on vm without any issues installed with 755 permissions.

**Comment by DerpyCrabs** [comment]
I found the reason. Downloaded zip from github and extracted by file-roller has 700 permissions of folders in installer path. I tried git clone and it's working. 775 permissions on folders.

**Comment by DerpyCrabs** [comment]
I found the reason. Downloaded zip from github and extracted by file-roller has 700 permissions of folders in installer path. I tried git clone and it's working. 775 permissions on folders.

**Comment by poltertec** [comment]
Allright thx for the clarification & glad it's resolved :)
