### ISSUE TITLE
The HeaderBar window controls have vanished

### ISSUE THREAD

**Issue by zesterer** [poltertec/evopop-gtk-theme#34]
The title says it all. No need for a screenshot. They still exist, I can click them. But visually they are non-existent.

**Comment by poltertec** [comment]
are we talking gtk 3.14 or mutter?

**Comment by poltertec** [comment]
Just downloaded the latest build on my computers & did not come across it.
On gtk 3.14 however left window controls haven't been implemented yet.
Will add it in a sec.

**Comment by zesterer** [comment]
Gtk 3.14, using Gala as a window manager. Although that shouldn't make a
difference I think as CSD are handled by the toolkit, not the WM.

On 6 April 2015 at 00:35, poltertec <notifications@github.com> wrote:

> are we talking gtk 3.14 or mutter?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/poltertec/evopop-gtk-theme/issues/34#issuecomment-89869205>
> .
>



-- 
Thanks,

Barry Smith

**Comment by poltertec** [comment]
Asked it to pinpoint the file i had to look in.
Anyway should work now grtz

**Comment by zesterer** [comment]
Thanks

On 6 April 2015 at 09:26, poltertec <notifications@github.com> wrote:

> Asked it to pinpoint the file i had to look in.
> Anyway should work now grtz
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/poltertec/evopop-gtk-theme/issues/34#issuecomment-89974082>
> .
>



-- 
Thanks,

Barry Smith
