### ISSUE TITLE
Inconsistent window button colors

### ISSUE THREAD

**Issue by alphaPhi** [poltertec/evopop-gtk-theme#7]
![windowbuttons](https://cloud.githubusercontent.com/assets/4603691/6320041/abe5b284-badc-11e4-89b0-8c04b64ce3cc.png)
The minimize and maximize buttons have different buttons on headerbar and titlebar.

**Comment by crutchcorn** [comment]
Just wondering - what changes in GTK3.16 allow this to be fixed and how will it be fixed? 
(just wanting to learn is all)

**Comment by poltertec** [comment]
https://git.gnome.org/browse/gtk+/commit/?id=b187773053098cca1b7c23e04e096d47fbb65a5f
No more nth-child stuff

**Comment by poltertec** [comment]
will have to drop 3.14 to fix this so will wait untill  ikey pushes 3.16 to evolve os

**Comment by ikeydoherty** [comment]
Well... :)

With 3.16 you can now have *versioned* themes!
